# Generated by Django 3.2.1 on 2021-05-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-date_created']},
        ),
    ]
