# Generated by Django 3.2.1 on 2021-05-17 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210517_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content_en',
            new_name='content_en_us',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='title_en',
            new_name='title_en_us',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='description_en',
            new_name='description_en_us',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='theme_en',
            new_name='theme_en_us',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='title_en',
            new_name='title_en_us',
        ),
    ]
